export const CommandLineArgs = {
    "instance-id": { path: "instance.id" },
    "instance-name": { path: "instance.name" },
    role: { path: "instance.role", short: "-r" },
    port: { path: "network.port", short: "-p" },
    host: { path: "network.host", short: "-H" },
    discovery: { path: "network.discovery.enabled" },
    "service-name": { path: "network.discovery.serviceName", short: "-s" },
    "screen-id": { path: "screen.id" },
    "screen-x": { path: "screen.position.x" },
    "screen-y": { path: "screen.position.y" },
    "screen-width": { path: "screen.dimensions.width" },
    "screen-height": { path: "screen.dimensions.height" },
    "screen-edges": { path: "screen.edges" },
    server: { path: "cluster.server.host" },
    "server-port": { path: "cluster.server.port" },
    peers: { path: "cluster.peers" },
    adjacency: { path: "cluster.adjacency" },
    "capture-mouse": { path: "input.capture.mouse" },
    "capture-keyboard": { path: "input.capture.keyboard" },
    "forward-events": { path: "input.forward" },
    "cursor-transition": { path: "input.cursorTransition.enabled" },
    "dead-zone": { path: "input.cursorTransition.deadZone" },
    "log-level": { path: "logging.level", short: "-l" },
    "log-file": { path: "logging.file", short: "-f" },
    dev: { path: "development.enabled", short: "-d" },
    "mock-input": { path: "development.mockInput" },
    console: { path: "console.enabled" }
};
